version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/faiss_index:/app/faiss_index

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
